# Generated by Django 6.0 on 2026-01-08 16:59
from django.utils import timezone
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]
    def create_superuser(apps,schema_editor):
        from django.contrib.auth import get_user_model
        
        User=get_user_model()

        if User.objects.filter(email="harshp4466@gmail.com").exists():
            return

        superuser=User.objects.create_superuser(
            email="harshp4466@gmail.com",
            password="harsh445566p",
            last_login=timezone.now()
        )
        
        superuser.save()
        
    operations = [
        migrations.RunPython(create_superuser)
    ]
