# Generated by Django 6.0 on 2026-01-31 09:19

from django.db import migrations
from allauth.account.models import EmailAddress
from allauth.account.utils import user_email


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_email'),
    ]

    def create_superuser(apps,schema_editor):
        from django.contrib.auth import get_user_model
        User=get_user_model()
        superuser=User.objects.get(email="harshp4466@gmail.com")
        
        email,created=EmailAddress.objects.get_or_create(
            user=superuser, email=user_email(superuser)
        )
        email.verified=True
        email.save()
    operations = [
        migrations.RunPython(create_superuser)
    ]
    
