"""
Django settings for djangoproject project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import dj_database_url
import os
import socket  # Moved import to top

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment state
ENV_STATE = os.getenv("ENV_STATE", "dev")

# SECURITY WARNING: keep the secret key used in production secret!
# FIXED: Added a fallback for local dev so it doesn't crash immediately if env var is missing
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-fallback-key-change-this-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Hosts/origins are environment-driven with safe local defaults.
ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "articleswriter-production.up.railway.app,.up.railway.app,127.0.0.1,localhost",
).split(",")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

default_csrf_origins = ",".join(
    [
        "https://articleswriter-production.up.railway.app",
        "https://*.up.railway.app",
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
)
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", default_csrf_origins).split(",")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]

railway_public_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
if railway_public_domain and railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_public_domain)
if railway_public_domain:
    railway_origin = f"https://{railway_public_domain}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

ADMIN_URL = os.getenv("ADMIN_URL", "admin")

# Production Security Settings
if ENV_STATE == "production":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    # create a strong security posture
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend", # Needed for standard login
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
    'django.contrib.sites',
]

THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'anymail',
    'widget_tweaks',
    'whitenoise.runserver_nostatic',
]

PROJECT_APPS = [
    "app.apps.AppConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Debug Toolbar & Reload configurations
if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
        'django_browser_reload',
    ]
    
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        'django_browser_reload.middleware.BrowserReloadMiddleware',
    ]
    
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        docker_ips = [ip[:-1] + "1" for ip in ips]
        INTERNAL_IPS = docker_ips + ["127.0.0.1"]
    except Exception:
        INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

AUTH_USER_MODEL = "app.UserProfile"

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

EMAIL_PROVIDER = os.getenv(
    "EMAIL_PROVIDER",
    "mailjet" if ENV_STATE == "production" else "console",
).lower()

if EMAIL_PROVIDER == "mailgun":
    DEFAULT_FROM_EMAIL = os.getenv("MAILGUN_EMAIL", "noreply@example.com")
    ANYMAIL = {
        "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY", "None"),
        "SEND_DEFAULTS": {"tags": {"django_project"}},
    }
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
elif EMAIL_PROVIDER == "mailjet":
    DEFAULT_FROM_EMAIL = os.getenv(
        "MAILJET_SENDER_EMAIL",
        os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com"),
    )
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("MAILJET_SMTP_HOST", "in-v3.mailjet.com")
    EMAIL_PORT = int(os.getenv("MAILJET_SMTP_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("MAILJET_API_KEY", "")
    EMAIL_HOST_PASSWORD = os.getenv("MAILJET_SECRET_KEY", "")
    EMAIL_USE_TLS = os.getenv("MAILJET_USE_TLS", "True").lower() == "true"
    EMAIL_USE_SSL = os.getenv("MAILJET_USE_SSL", "False").lower() == "true"
else:
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend",
    )

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'account_login'

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False

LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale"
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage"
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}
