"""
Django settings for djangoproject project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import dj_database_url
import os
import socket  # Moved import to top
import logging


def _env(name: str, default: str = "") -> str:
    value = os.getenv(name, default)
    return value.strip().strip("'").strip('"')


def _env_csv(name: str, default: str) -> list[str]:
    raw = _env(name, default)
    return [item.strip().strip("'").strip('"') for item in raw.split(",") if item.strip()]


def _env_bool(name: str, default: bool = False) -> bool:
    fallback = "True" if default else "False"
    return _env(name, fallback).lower() == "true"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
logger = logging.getLogger(__name__)

# Load environment state
ENV_STATE = _env("ENV_STATE", "dev")

# SECURITY WARNING: keep the secret key used in production secret!
# FIXED: Added a fallback for local dev so it doesn't crash immediately if env var is missing
SECRET_KEY = _env("SECRET_KEY", "django-insecure-fallback-key-change-this-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", False)

# Hosts/origins are environment-driven with safe local defaults.
ALLOWED_HOSTS = _env_csv(
    "ALLOWED_HOSTS",
    "articleswriter-production.up.railway.app,.up.railway.app,127.0.0.1,localhost",
)

default_csrf_origins = ",".join(
    [
        "https://articleswriter-production.up.railway.app",
        "https://*.up.railway.app",
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
)
CSRF_TRUSTED_ORIGINS = _env_csv("CSRF_TRUSTED_ORIGINS", default_csrf_origins)

railway_public_domain = _env("RAILWAY_PUBLIC_DOMAIN", "")
if railway_public_domain and railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_public_domain)
if railway_public_domain:
    railway_origin = f"https://{railway_public_domain}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

ADMIN_URL = _env("ADMIN_URL", "admin")

# Production Security Settings
if ENV_STATE == "production":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    # create a strong security posture
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend", # Needed for standard login
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
    'django.contrib.sites',
]

THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'anymail',
    'widget_tweaks',
    'whitenoise.runserver_nostatic',
]

PROJECT_APPS = [
    "app.apps.AppConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Debug Toolbar & Reload configurations
if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
        'django_browser_reload',
    ]
    
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        'django_browser_reload.middleware.BrowserReloadMiddleware',
    ]
    
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        docker_ips = [ip[:-1] + "1" for ip in ips]
        INTERNAL_IPS = docker_ips + ["127.0.0.1"]
    except Exception:
        INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'

DATABASE_URL = _env("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
    )
}

if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"].setdefault("OPTIONS", {})
    # Fail fast when DB host is unreachable to avoid hanging requests.
    DATABASES["default"]["OPTIONS"]["connect_timeout"] = int(
        _env("DB_CONNECT_TIMEOUT", "5")
    )

AUTH_USER_MODEL = "app.UserProfile"

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

EMAIL_PROVIDER = os.getenv(
    "EMAIL_PROVIDER",
    "mailjet" if ENV_STATE == "production" else "console",
).strip().strip("'").strip('"').lower()

if EMAIL_PROVIDER == "mailgun":
    DEFAULT_FROM_EMAIL = _env("MAILGUN_EMAIL", "noreply@example.com")
    mailgun_api_key = _env("MAILGUN_API_KEY", "")
    if not mailgun_api_key or mailgun_api_key.lower() == "none":
        logger.warning(
            "EMAIL_PROVIDER=mailgun but MAILGUN_API_KEY is missing; using console email backend."
        )
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        ANYMAIL = {
            "MAILGUN_API_KEY": mailgun_api_key,
            "SEND_DEFAULTS": {"tags": {"django_project"}},
            "REQUESTS_TIMEOUT": int(_env("EMAIL_TIMEOUT", "8")),
        }
        mailgun_sender_domain = _env("MAILGUN_SENDER_DOMAIN", "")
        if mailgun_sender_domain:
            ANYMAIL["MAILGUN_SENDER_DOMAIN"] = mailgun_sender_domain
        EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
elif EMAIL_PROVIDER == "mailjet":
    DEFAULT_FROM_EMAIL = _env(
        "MAILJET_SENDER_EMAIL",
        _env("DEFAULT_FROM_EMAIL", "noreply@example.com"),
    )
    EMAIL_HOST_USER = _env("MAILJET_API_KEY", "")
    EMAIL_HOST_PASSWORD = _env("MAILJET_SECRET_KEY", "")
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        logger.warning(
            "EMAIL_PROVIDER=mailjet but credentials are missing; using console email backend."
        )
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        # Use Mailjet API instead of SMTP to avoid outbound SMTP timeout issues.
        ANYMAIL = {
            "MAILJET_API_KEY": EMAIL_HOST_USER,
            "MAILJET_SECRET_KEY": EMAIL_HOST_PASSWORD,
            "REQUESTS_TIMEOUT": int(_env("EMAIL_TIMEOUT", "8")),
        }
        EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
else:
    DEFAULT_FROM_EMAIL = _env("DEFAULT_FROM_EMAIL", "noreply@example.com")
    EMAIL_BACKEND = _env(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend",
    )

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'account_login'
EMAIL_FAIL_SILENTLY = _env_bool("EMAIL_FAIL_SILENTLY", ENV_STATE != "production")

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_ADAPTER = "app.adapters.SafeAccountAdapter"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" if ENV_STATE == "production" else "http"

LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale"
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage"
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}
